### ISSUE TITLE
Conversion factors need to be updated and scaling seems to be wrong

### ISSUE THREAD

**Issue by eichstaedtPTB** [harislulic/ZeMA-machine-learning-tutorials#32]
In `0_Data_Import_and_Visualisation.ipynb` the out-dated conversion factors are used, that lead to non-SI units, such as "g" for acceleration. The updated table is available on Zenodo and should be used instead.

Also, the scaling seems to be wrongly implemented for the plotting, because the amplitudes of the signals before and after the scaling are identical. For instance, the microphone data in Pa should be around +/- 0.4 instead of +/- 200000.

**Comment by harislulic** [comment]
Dear Sascha,
thank you for your comments and for opening these issues. Conversion factors are now updated with the new version. Regarding the second issue: there is an option to run the code skipping the conversion step, and that case was shown before. If one runs the cell with the conversion step, then it is okay.

Best regards

**Comment by eichstaedtPTB** [comment]
Great! Thanks for correcting this so quickly.
